@tool
extends Node3D

@export var scopeLength:float = 4096
var initDone:bool = false

# Called when the node enters the scene tree for the first time.
func _ready():
#	print_debug("_ready\t",Time.get_ticks_msec(),"\t",self.get_path())
	if ((!Global) ||(Engine.is_editor_hint() && Global.cleanTempToolData)):
		# @tool-scripts will generate changes that are saved into .tscn (scene)-files.
		# Clean them when requested
		
		print("Cleaning data generated by @tool, ", self.name)
		$Surface.material_override = null

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta):
	# No need for any initializations here as the material is shared
	pass
